### PR TITLE
replace deprecated functions

### PR DESCRIPTION
**Pull request by WhiffleFish**
`n_actions` and `n_states` no longer supported by POMDPs.jl
`POMDPs.n_actions` -> `n_actions`
`POMDPs.n_states` -> `n_states`

`SIRParticleFilter` has since been renamed to `BootstrapFilter`
`ParticleFilters.SIRParticleFilter` -> `ParticleFilters.BootstrapFilter`

### CODE REVIEW

**Review by zsunberg — CHANGES_REQUESTED** [review]
Thanks for fixing these things!

We should also update the Project.toml. Ideally every dependency should have an entry in the [compat] section, but I think we should at least create a compat section with POMDPs at 0.9 since these changes will only work with that.

**Comment by zsunberg** [comment]
Should I merge this?

**Comment by WhiffleFish** [comment]
Alright, this should be good to merge now. Also, should we move this over to JuliaPOMDP?

**Comment by zsunberg** [comment]
Thanks @WhiffleFish ! Looks good!

**Review by zsunberg — COMMENTED** [review]
Looks good

**Pull request merged**
